/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.vitals;

import business.EcoSystem;
import business.enterprise.Enterprise;
import business.organization.Organization;
import business.organization.OrganizationDirectory;
import business.patient.Patient;
import business.patient.vitalSigns.VitalSigns;
import business.userAccount.UserAccount;
import calculations.Calculate;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.exercise.ManageExerciseJPanel;
import userInterface.meals.ViewMealsJPanel;
import userInterface.medication.ManageMedicationJPanel;
import userInterface.patient.RequestAppointmentJPanel;

/**
 *
 * @author Prajakta
 */
public class ManageVitalsJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Patient patient;
    private OrganizationDirectory organizationDirectory;
    private EcoSystem business;
    /**
     * Creates new form ManageVitalsJPanel
     */
    public ManageVitalsJPanel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory,UserAccount account, Enterprise enterprise,EcoSystem business) {
        initComponents();
        setSize(1370, 725);
        this.business = business;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        this.patient = (Patient) userAccount.getPerson();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblEntValue = new javax.swing.JLabel();
        lblVitals = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRecord = new javax.swing.JButton();
        btnProgress = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRecordMeal = new javax.swing.JButton();
        btnRecordMed = new javax.swing.JButton();
        btnRecordExercise = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();

        lblWelcome.setText("Welcome");

        lblEntValue.setText("<value>");

        lblVitals.setText("Profile Dashboard");

        btnRecord.setText("Track Vitals");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        btnProgress.setText("Show my progress");
        btnProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProgressActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRecordMeal.setText("Track Meal");
        btnRecordMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordMealActionPerformed(evt);
            }
        });

        btnRecordMed.setText("Track Medications");
        btnRecordMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordMedActionPerformed(evt);
            }
        });

        btnRecordExercise.setText("Track Exercise");
        btnRecordExercise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordExerciseActionPerformed(evt);
            }
        });

        btnAppointment.setText("Make an Appointment");
        btnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRecordExercise, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecordMed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecordMeal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(29, 29, 29)
                        .addComponent(lblEntValue, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVitals, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome)
                    .addComponent(lblEntValue)
                    .addComponent(lblVitals))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecordMeal)
                    .addComponent(btnProgress))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecord)
                    .addComponent(btnAppointment))
                .addGap(34, 34, 34)
                .addComponent(btnRecordMed)
                .addGap(27, 27, 27)
                .addComponent(btnRecordExercise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        // TODO add your handling code here:
        ViewVitalsJPanel viewVitalsJPanel = new ViewVitalsJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), userAccount);
        userProcessContainer.add("viewVitalsJPanel", viewVitalsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnRecordActionPerformed

    private void btnProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProgressActionPerformed
        // TODO add your handling code here:
        ProgressJPanel progressJPanel = new ProgressJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),userAccount,business);
        userProcessContainer.add("progressJPanel", progressJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProgressActionPerformed

    private void btnRecordMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordMealActionPerformed
        // TODO add your handling code here:
        ViewMealsJPanel viewMealsJPanel = new ViewMealsJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), userAccount);
        userProcessContainer.add("viewMealsJPanel", viewMealsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnRecordMealActionPerformed

    private void btnRecordMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordMedActionPerformed
        // TODO add your handling code here:
        ManageMedicationJPanel manageMedicationJPanel = new ManageMedicationJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), userAccount);
        userProcessContainer.add("manageMedicationJPanel", manageMedicationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRecordMedActionPerformed

    private void btnRecordExerciseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordExerciseActionPerformed
        // TODO add your handling code here:
        ManageExerciseJPanel manageExerciseJPanel = new ManageExerciseJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), userAccount);
        userProcessContainer.add("manageExerciseJPanel", manageExerciseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRecordExerciseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestAppointmentJPanel", new RequestAppointmentJPanel(userProcessContainer, userAccount, enterprise,business));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAppointmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProgress;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnRecordExercise;
    private javax.swing.JButton btnRecordMeal;
    private javax.swing.JButton btnRecordMed;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEntValue;
    private javax.swing.JLabel lblVitals;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
